# Generated by Django 4.1.3 on 2022-11-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('view_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.TextField()),
                ('vcreated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'blog_views',
            },
        ),
    ]
